[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
shared = { path = "../shared" }
libsodium-sys-stable = "1.22.3"
libc = "0.2.172"
color-eyre = "0.6.4"
