[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
bincode = "1.3.3"
chrono = "0.4.41"
native-tls = { version = "0.2.14", features = ["vendored"] }
shared = { path = "../shared" }
sled = "0.34.7"
