[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
libc = "0.2.172"
libsodium-sys-stable = "1.22.3"
serde = { version = "1.0.219", features = ["derive"] }
tabled = "0.19.0"
