@startuml
title Download

participant Recipient
participant Server
database Database

note over Recipient
  Retrieve keys
end note

Recipient ->> Server: <math>I_r || I_m || \tau</math>
Server ->> Database: Request
Database ->> Server: <math>U_r</math>

note over Server
  <math>S_{sr} = DH(U_r, P_s)</math>
end note

note over Server
  <math>"Check "\tau</math>
end note

Server ->> Database: Request
Database ->> Server: <math>E_{S_m}^{k_3}(E_{S_{cr}}^{k_1}(M) || k_1 ) || k_3 </math>
Server ->> Recipient: <math>E_{S_m}^{k_3}(E_{S_{cr}}^{k_1}(M) || k_1 ) || k_3 || \tau</math>

note over Recipient
  <math>"Check " \tau</math>
end note
@enduml