@startuml
title Download

participant Recipient
participant Server
database Database

Recipient ->> Server: <math>I_r || I_m || S_{"auth"}</math>
Server ->> Database: Request
Database ->> Server: <math>S_{"auth"}</math>


rnote over Server
  <math>"Check "S_{"auth"}</math>
end rnote

Server ->> Database: Request
Database ->> Server: <math>U_c || E_{S_m}^{k_2}(M) || k_2 || \tau_"data"</math>
Server ->> Recipient: <math>U_c || E_{S_m}^{k_2}(M) || k_2 || \tau_"data"</math>

rnote over Recipient
<math>S_{cr} = DH(U_c, P_r)</math>
end rnote

rnote over Recipient
<math>"Check "\tau_"data"</math>
end rnote

@enduml