@startuml
participant Client
participant Server
database Database

note over Client
  <math>S_c, P_c</math>
end note

note over Client
  <math>"hash" = H("pass")</math>
end note

note over Client
  <math>W_c = HKDF("hash")</math>
end note

Client ->> Server: <math>I_c || P_c || E_W_c(S_c)</math>

note over Server
  How to verify public key wasn't spoofed? -> TLS
end note

Server ->> Database: <math>I_c || P_c || E_W_c(S_c)</math>
@enduml