@startuml
participant Client
participant Server
database Database

note over Client
  <math>"Pick asymmtric keys " P_c, U_c</math>
end note

note over Client
  <math>"hash" = H("pass")</math>
end note

note over Client
  <math>W_c = HKDF("hash")</math>
end note

Client ->> Server: <math>I_c || U_c || E_{W_c}(P_c)</math>

Server ->> Database: <math>I_c || U_c || E_{W_c}(P_c)</math>
@enduml