@startuml
title Key structure

rectangle "Password" as P
rectangle "Master Key" as MK
rectangle "Shared Key" as SK
rectangle "Encryption Key" as EK
rectangle "Authentication Key" as AK
rectangle "Private Key" as PK
rectangle "Public Key" as UK
rectangle "Encrypted Private Key" as EPK
rectangle "Public Key of Server/Recipient" as UKR


circle "Hash()" as H
circle "Diffie-Hellman()" as DH
circle "Encrypt()" as E
circle "HKDF()" as HKDF


P -> H
H -> MK
MK -> HKDF
HKDF --> AK
HKDF -> EK
PK .. UK

EK --> E
PK -> E
E -> EPK

UKR -> DH
PK --> DH
DH -> SK

@enduml
