@startuml
participant Recipient
participant Server
database Database

note over Recipient
  Retrieve keys
end note

Recipient ->> Server: <math>I_r || I_m || \tau</math>
Server ->> Database: Request
Database ->> Server: <math>U_r</math>

note over Server
  <math>S_{sr} = DH(U_r, P_s)</math>
end note

note over Server
  <math>"Check "\tau</math>
end note

Server ->> Database: Request
Database ->> Server: <math>I_{m_1} || I_{m_2} || \cdots || I_{m_n} </math>
Server ->> Recipient: <math>I_{m_1} || I_{m_2} || \cdots || I_{m_n} || \tau</math>

note over Recipient
  <math>"Check "\tau</math>
end note

@enduml