@startuml
participant Client
participant Server
database Database

note over Client
  Retrieve keys
end note

note over Client
  Derive key from new password
end note

note over Client
  <math>"Pick " k_1, k_2</math>
end note

Client ->> Server: <math>I_c || E_{S_{cs}}^{k_1}(E_{W_c}^{k_2}(P_c)) || k_2 || k_1 || \tau</math>
Server ->> Database: Request
Database ->> Server: <math>U_c</math>

note over Server
    <math>S_{cs} = DH(U_c, P_s)</math>
end note

note over Server
    <math>"Check " \tau</math>
end note

note over Server
    <math>E_{W_c}^{k_2}(P_c) = D_{S_{cs}}^{k_1}(E_{S_{cs}}^{k_1}(E_{W_c}^{k_2}(P_c)))</math>
end note



Server ->> Database: <math>E_{W_c}^{k_2}(P_c) || k_2</math>
@enduml