@startuml
participant Client
participant Server
database Database

note over Client
  Retrieve keys
end note

note over Client
  Encrypt private key using new password
end note

Client ->> Server: <math>E_{S_{cs}}(E_{W_c}(P_c)) || \tau</math>


note over Server
    <math>"Check " \tau</math>
end note


Server ->> Database: <math>E_{W_c}(P_c)</math>
@enduml