@startuml
participant Client
participant Server
database Database

note over Client
  Retrieve keys
end note

note over Client
  Encrypt private key using new password
end note

Client ->> Server: <math>I_c || E_{S_{cs}}(E_{W_c}(P_c)) || \tau</math>
Server ->> Database: Request
Database ->> Server: <math>U_c</math>

note over Server
    <math>S_{cs} = DH(U_c, P_s)</math>
end note

note over Server
    <math>"Check " \tau</math>
end note

note over Server
    <math>E_{W_c} = D_{S_{cs}}(E_{S_{cs}}(E_{W_c}))</math>
end note



Server ->> Database: <math>E_{W_c}(P_c)</math>
@enduml