@startuml
participant Client
participant Server
database Database

Client ->> Server: Request
Server ->> Database: Request
Database ->> Server: <math>E_W_c(S_c)</math>
Server ->> Client: <math>E_W_c(S_c) || U_s</math>

note over Client
  Decrypt private key using old password
end note

note over Client
  Encrypt private key using new password
end note

Client ->> Server: <math>E_U_s(E_W_c(S_c))</math>

Server ->> Database: <math>E_W_c(S_c)</math>
@enduml