@startuml
participant Client
participant Server
database Database

Client ->> Server: Request
Server ->> Database: Request
Database ->> Server: <math>E_W_c(S_c)</math>
Server ->> Client: <math>E_W_c(S_c) || U_s</math>

note over Client
  <math>"hash" = H("pass")</math>
end note

note over Client
  <math>W_c = HKDF("hash")</math>
end note


Client ->> Server: <math>E_U_s(E_W_c(S_c))</math>

Server ->> Database: <math>E_W_c(S_c)</math>
@enduml