@startuml
title Retrieve keys
participant Client
participant Server
database Database

Client ->> Server: <math>I_c</math>
Server ->> Database: Request
Database ->> Server: <math>a</math>
Server ->> Client: <math>a</math>


rnote over Client
  <math>S_"master" = H_s("pass")</math>
end rnote
rnote over Client
  <math>S_"auth" = "HKDF"(S_"master")</math>
end rnote
rnote over Client
  <math>S_"enc" = "HKDF"(S_"master")</math>
end rnote

Client ->> Server: <math>I_c || S_"auth"</math>
Server ->> Database: Request
Database ->> Server: <math>S_"auth"</math>

rnote over Server
<math>"Check " S_"auth"</math>
end rnote

Server ->> Database: Request
Database ->> Server: <math>E_{S_"enc"}^k(P_c) || k</math>

Server ->> Client: <math>E_{S_"enc"}^k(P_c) || k</math>

rnote over Client
  <math>P_c = D_{S_"enc"}^k(E_{S_"enc"}^k(P_c))</math>
end rnote


@enduml