@startuml
title Send message
participant Client
participant Server
database Database


rnote over Client
  <math>\tau = "MAC"_{S_{cs}}(I_r || I_c)</math>
end rnote

Client ->> Server: <math>(I_r || I_c) || \tau</math>

Server ->> Database: Request
Database ->> Server: <math>U_r || U_c</math>

rnote over Server
  <math>S_{cs} = "DH"(U_c, P_s)</math>
end rnote

rnote over Server
  <math>"Check " \tau</math>
end rnote

Server ->> Client: <math>U_r</math>

rnote over Client
  <math>S_{cr} = "DH"(U_r, P_c)</math>
end rnote

rnote over Client
  <math>"Pick "k_1, k_2, S_m</math>
end rnote

rnote over Client
  <math>\tau_{"key"} = "MAC"_{S_{cr}}(E_{S_{cr}}^{k_1}(S_m) || k_1)</math>
end rnote

rnote over Client
  <math>\tau_{"data"} = "MAC"_{S_{cr}}(E_{S_m}^{k_2}(M) || k_2)</math>
end rnote

rnote over Client
<math>"Select unlock time " t</math>
end rnote

rnote over Client
  <math>\tau = "MAC"_{S_{cs}}(t || (E_{S_{cr}}^{k_1}(S_m) || k_1) || \tau_"key" || (E_{S_m}^{k_2}(M) || k_2) || \tau_"data") </math>
end rnote


Client ->> Server: <math>(t ||(E_{S_{cr}}^{k_1}(S_m) || k_1) || \tau_"key" || (E_{S_m}^{k_2}(M) || k_2) || \tau_"data") || \tau</math>

rnote over Server
  <math>"Check " \tau</math>
end rnote


Server ->> Database: <math>t || (E_{S_{cr}}^{k_1}(S_m) || k_1) || \tau_"key" || (E_{S_m}^{k_2}(M) || k_2) || \tau_"data"</math>
@enduml