@startuml
title Unlock message
participant Recipient
participant Server
database Database


Recipient ->> Server: <math>I_r || I_m || S_"auth"</math>
Server ->> Database: Request
Database ->> Server: <math>S_"auth"</math>

rnote over Server
  <math>"Check " S_"auth"</math>
end rnote

Server ->> Database: Request
Database ->> Server: <math>t</math>

rnote over Server
  <math>"Check "t</math>
end rnote


Server ->> Database: Request
Database ->> Server: <math>U_c || (E_{S_{cr}}^{k_2}(S_m) || k_2) || \tau_"key"</math>
Server ->> Recipient: <math>U_c ||(E_{S_{cr}}^{k_2}(S_m) || k_2) || \tau_"key"</math>

rnote over Recipient
<math>S_{cr} = DH(U_c, P_r)</math>
end rnote

rnote over Recipient
<math>"Check " \tau_"key"</math>
end rnote

rnote over Recipient
<math>S_m = D_{S_{cr}}^{k_2}(E_{S_{cr}}^{k_2}(S_m))</math>
end rnote

rnote over Recipient
<math>M = D_{S_m}^{k_1}(E_{S_m}^{k_1}(M))</math>
end rnote

@enduml