@startuml
title Unlock message
participant Recipient
participant Server
database Database

note over Recipient
  Retrieve keys
end note

Recipient ->> Server: <math>I_r || I_m || \tau</math>
Server ->> Database: Request
Database ->> Server: <math>U_r</math>

note over Server
  <math>S_{sr} = DH(U_r, P_s)</math>
end note

note over Server
  <math>"Check "\tau</math>
end note

Server ->> Database: Request
Database ->> Server: <math>t</math>

note over Server
  <math>"Check "t</math>
end note


Server ->> Database: Request
Database ->> Server: <math>S_m || \tau_1</math>

note over Server
  <math>"Pick "k_1</math>
end note

Server ->> Recipient: <math>E_{S_{sr}}^{k_1}(S_m || \tau_1) || k_1 || \tau_2</math>


note over Recipient
  <math>"Check " \tau_2</math>
end note

note over Recipient
  <math>S_m, \tau_1 = D_{S_{sr}}^{k_1}(E_{S_{sr}}(S_m||\tau_1))</math>
end note

note over Recipient
  <math>E_{S_{cr}}^{k_2}(M), k_2 = D_{S_m}^{k_1}(E_{S_m}^{k_1}(E_{S_{cr}}^{k_2}(M)|| k_2))</math>
end note

note over Recipient
  <math>M = D_{S_{cr}}^{k_2}(E_{S_{cr}}^{k_2}(M))</math>
end note

note over Recipient
  <math>"Check " \tau_1</math>
end note


@enduml