name: Document

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Write certificate and key files
        run: |
          mkdir -p ./client ./server
          echo "${{ secrets.SERVER_CERT }}" > ./client/src/server.crt
          echo "${{ secrets.SERVER_KEY }}" > ./server/src/server.key
          echo "${{ secrets.SERVER_PEM }}" > ./server/src/server.pem
          
      - name: Build docs
        run: cargo doc --workspace --no-deps
