name: Document

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs
        run: cargo doc --workspace --no-deps
