name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build client
        run: cargo build --release --package client

      - name: Build server
        run: cargo build --release --package server

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/client
            target/release/server
