name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  releases: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Write certificate and key files
        run: |
          echo "${{ secrets.SERVER_CERT }}" > ./client/src/cert.pem
          echo "${{ secrets.SERVER_KEY }}" > ./server/src/key.pem
          echo "${{ secrets.SERVER_CERT }}" > ./server/src/cert.pem
          
      - name: Build client
        run: cargo build --release --package client

      - name: Build server
        run: cargo build --release --package server

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/tl
            target/release/timelock-server
