name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Write certificate and key files
        run: |
          mkdir -p ./client ./server
          echo "${{ secrets.SERVER_CERT }}" > ./client/src/server.crt
          echo "${{ secrets.SERVER_KEY }}" > ./server/src/server.key
          echo "${{ secrets.SERVER_PEM }}" > ./server/src/server.pem
          
      - name: Build client
        run: cargo build --release --package client

      - name: Build server
        run: cargo build --release --package server

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/client
            target/release/server
