name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write certificate and key files
        run: |
          echo "${{ secrets.SERVER_CERT }}" > ./client/src/cert.pem
          echo "${{ secrets.SERVER_KEY }}" > ./server/src/key.pem
          echo "${{ secrets.SERVER_CERT }}" > ./server/src/cert.pem

      - name: Install rustup targets
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Build client for linux
        run: cargo build --release --package client --target x86_64-unknown-linux-gnu

      - name: Build server for linux
        run: cargo build --release --package server --target x86_64-unknown-linux-gnu

      - name: Rename and Upload release assets for linux
        run: |
          mv target/x86_64-unknown-linux-gnu/release/timelock-client target/x86_64-unknown-linux-gnu/release/timelock-client-${{ github.ref_name }}-linux-x86_64
          mv target/x86_64-unknown-linux-gnu/release/timelock-server target/x86_64-unknown-linux-gnu/release/timelock-server-${{ github.ref_name }}-linux-x86_64
      
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/timelock-client-${{ github.ref_name }}-linux-x86_64
            target/x86_64-unknown-linux-gnu/release/timelock-server-${{ github.ref_name }}-linux-x86_64

  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write certificate and key files
        run: |
          echo "${{ secrets.SERVER_CERT }}" > ./client/src/cert.pem
          echo "${{ secrets.SERVER_KEY }}" > ./server/src/key.pem
          echo "${{ secrets.SERVER_CERT }}" > ./server/src/cert.pem

      - name: Install rustup targets
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build client for windows
        run: cargo build --release --package client --target x86_64-pc-windows-msvc

      - name: Build server for windows
        run: cargo build --release --package server --target x86_64-pc-windows-msvc

      - name: Rename and Upload release assets for windows
        run: |
          mv target/x86_64-pc-windows-msvc/release/timelock-client.exe target/x86_64-pc-windows-msvc/release/timelock-client-${{ github.ref_name }}-windows-x86_64.exe
          mv target/x86_64-pc-windows-msvc/release/timelock-server.exe target/x86_64-pc-windows-msvc/release/timelock-server-${{ github.ref_name }}-windows-x86_64.exe
      
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            target/x86_64-pc-windows-msvc/release/timelock-client-${{ github.ref_name }}-windows-x86_64.exe
            target/x86_64-pc-windows-msvc/release/timelock-server-${{ github.ref_name }}-windows-x86_64.exe

  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Write certificate and key files
        run: |
          echo "${{ secrets.SERVER_CERT }}" > ./client/src/cert.pem
          echo "${{ secrets.SERVER_KEY }}" > ./server/src/key.pem
          echo "${{ secrets.SERVER_CERT }}" > ./server/src/cert.pem

      - name: Install rustup targets
        run: rustup target add x86_64-apple-darwin

      - name: Build client for macOS
        run: cargo build --release --package client --target x86_64-apple-darwin

      - name: Build server for macOS
        run: cargo build --release --package server --target x86_64-apple-darwin

      - name: Rename and Upload release assets for macOS
        run: |
          mv target/x86_64-apple-darwin/release/timelock-client target/x86_64-apple-darwin/release/timelock-client-${{ github.ref_name }}-macos-x86_64
          mv target/x86_64-apple-darwin/release/timelock-server target/x86_64-apple-darwin/release/timelock-server-${{ github.ref_name }}-macos-x86_64
        
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            target/x86_64-apple-darwin/release/timelock-client-${{ github.ref_name }}-macos-x86_64
            target/x86_64-apple-darwin/release/timelock-server-${{ github.ref_name }}-macos-x86_64
